### ISSUE TITLE
Missing Library libpsanker.

### ISSUE THREAD

**Issue by ChemicalDatas** [TVPT/VoxelGuest#30]
Not sure how this one came about. 
Voxel Guest v 242
Maybe I missed somthing?

2012-10-05 08:19:57 [SEVERE] Could not load 'plugins\VoxelGuest.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: libpsanker
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:223)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:199)
    at net.minecraft.server.ServerConfigurationManagerAbstract.<init>(ServerConfigurationManagerAbstract.java:50)
    at net.minecraft.server.ServerConfigurationManager.<init>(SourceFile:11)
    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:105)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:377)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

**Comment by Spiritwo** [comment]
I too am having this error, would be nice to know what's wrong with it.

**Comment by MikeMatrix** [comment]
I'm curious why nobody has replied to this issue yet.
This is happening because it's depending on an external library written by the former lead developer of this plugin, but it is not included into the package that is being assembled.
You can download this library here:
https://github.com/psanker/libpsanker/blob/master/releases/com/patrickanker/libpsanker/1.4.3/libpsanker-1.4.3.jar?raw=true

Just put it into your plugins folder as usual.

**Comment by srmorris2** [comment]
I am now getting this error on VoxelGuest 4.2.5, and I added the most recent libpsanker 1.4.4 I could find. Is there a working configuration that I can use? I am really looking for a good Greylist solution!

**Comment by nristock** [comment]
Dependency has been removed in 5.x.x - close
