### ISSUE TITLE
Join Event Bug

### ISSUE THREAD

**Issue by itsjoekent** [TVPT/VoxelGuest#6]
Quoted from here = http://thevoxelbox.com/forum/minecraft-mods-plugins/voxelguest-issue-t1277.html#p11540

Whenever somebody joins, this happens

09:04:30 [SEVERE] Could not pass event PlayerJoinEvent to VoxelGuest
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:459)
at net.minecraft.server.ServerConfigurationManager.c(ServerConfigurationManager.java:132)
at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:129)
at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:41)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:61)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:567)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
at com.thevoxelbox.voxelguest.SimpleFormatter.format(SimpleFormatter.java:63)
at com.thevoxelbox.voxelguest.SystemListener.formatJoinQuitKickMessage(SystemListener.java:231)
at com.thevoxelbox.voxelguest.SystemListener.onPlayerJoin(SystemListener.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
... 9 more

Bans and kicks work, but gag doesn't, and no groups were generated in the groups folder. Using Ubuntu 12.04 if that makes any difference.

Also, using Bukkit 1.2.5-R3.0

**Comment by psanker** [comment]
Groups only generate if the player logging in has a defined group in his permissions setup.
